using System;
using DevExpress.Xpo;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;

namespace Cdb.Tickets.BusinessObjects
{
    [DefaultClassOptions]
    public class Ticket : BaseObject
    {        
        #region Private declarations
        private int ticketNumber; // should be Autogenerated i.e Auto Increment (need to research to see if it is possible in XPO or should it be manually autogenerated through code)
        private DateTime creationDate;
        private DateTime errorOccurDate;
        private DateTime errorIdentifiedDate;
        private string ticketDescription;
        private string followUp;

        private TicketSource ticketSourceId;
        private TicketState ticketStateId;
        private TicketType ticketTypeId;
        private Priority priorityId;
        private InternalUser raisedBy;
        private InternalUser assignedTo;
        private Client clientId;
        
        #endregion
        public Ticket(Session session)
            : base(session)
        {
        }
        public override void AfterConstruction()
        {
            base.AfterConstruction();
            CreationDate = DateTime.Now;
        }

        #region Columns
        public int TicketNumber
        {
            get
            {
                return ticketNumber;
            }
            set
            {
                SetPropertyValue("TicketNumber", ref ticketNumber, value);
            }
        }
        public DateTime CreationDate
        {
            get
            {
                return creationDate;
            }
            set
            {
                SetPropertyValue("CreationDate", ref creationDate, value);
            }
        }
        public DateTime ErrorOccurDate
        {
            get
            {
                return errorOccurDate;
            }
            set
            {
                SetPropertyValue("ErrorOccurDate", ref errorOccurDate, value);
            }
        }
        public DateTime ErrorIdentifiedDate
        {
            get
            {
                return errorIdentifiedDate;
            }
            set
            {
                SetPropertyValue("errorIdentifiedDate", ref errorIdentifiedDate, value);
            }
        }
        public string TicketDescription
        {
            get
            {
                return ticketDescription;
            }
            set
            {
                SetPropertyValue("TicketDescription", ref ticketDescription, value);
            }
        }
        public string FollowUp
        {
            get
            {
                return followUp;
            }
            set
            {
                SetPropertyValue("FollowUp", ref followUp, value);
            }
        }
        #endregion    

        #region Foreign Keys
        [Association("Priority-Tickets"), ImmediatePostData]
        [DisplayName("Priority")]
        public Priority PriorityId
        {
            get
            {
                return priorityId;
            }
            set
            {
                SetPropertyValue("Priority", ref priorityId, value);
            }
        }


        [Association("TicketSource-Tickets"), ImmediatePostData]
        [DisplayName("Source")]
        public TicketSource TicketSourceId
        {
            get
            {
                return ticketSourceId;
            }
            set
            {
                SetPropertyValue("TicketSourceId", ref ticketSourceId, value);
            }
        }

        [Association("TicketState-Tickets") , ImmediatePostData]
        [DisplayName("State")]
        public TicketState TicketStateId
        {
            get
            {
                return ticketStateId;
            }
            set
            {
                SetPropertyValue("TicketStateId", ref ticketStateId, value);
            }
        }

        [Association("TicketType-Tickets"), ImmediatePostData]
        [DisplayName("Type")]
        public TicketType TicketTypeId
        {
            get
            {
                return ticketTypeId;
            }
            set
            {
                SetPropertyValue("TicketTypeId", ref ticketTypeId, value);
            }
        }

        [Association("InternalUser-TicketsRaisedBy"),ImmediatePostData]
        public InternalUser RaisedBy
        {
            get
            {
                return raisedBy;
            }
            set
            {
                SetPropertyValue("RaisedBy", ref raisedBy, value);
            }
        }

        [Association("InternalUser-TicketsAssignedTo"), ImmediatePostData]
        public InternalUser AssignedTo
        {
            get
            {
                return assignedTo;
            }
            set
            {
                SetPropertyValue("AssignedTo", ref assignedTo, value);
            }
        }

        [Association("Client-Tickets"), ImmediatePostData]
        [DisplayName("Client")]
        public Client ClientId
        {
            get
            {
                return clientId;
            }
            set
            {
                SetPropertyValue("ClientId", ref clientId, value);
            }
        }
        #endregion

        #region OneToMany
        [Association("Ticket-Comments"), Aggregated]
        public XPCollection<Comment> Comments
        {
            get
            {
                return GetCollection<Comment>("Comments");
            }
        }
        [Association("Ticket-TicketResponses"), Aggregated]
        public XPCollection<TicketResponse> TicketResponses
        {
            get
            {
                return GetCollection<TicketResponse>("TicketResponses");
            }
        }
        #endregion
    }    
}