using System;
using System.Linq;
using System.Text;
using DevExpress.Xpo;
using DevExpress.ExpressApp;
using System.ComponentModel;
using DevExpress.ExpressApp.DC;
using DevExpress.Data.Filtering;
using DevExpress.Persistent.Base;
using System.Collections.Generic;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Persistent.Validation;

namespace Cdb.Tickets.BusinessObjects
{
    [DefaultClassOptions]
    public class Ticket : BaseObject
    {
        // Inherit from a different class to provide a custom primary key, concurrency and deletion behavior, etc. (https://documentation.devexpress.com/eXpressAppFramework/CustomDocument113146.aspx).
        #region Private declarations
        private int ticketNumber; // should be Autogenerated i.e Auto Increment (need to research to see if it is possible in XPO or should it be manually autogenerated through code)
        private DateTime creationDate;
        private DateTime errorOccurDate;
        private DateTime errorIdentifiedDate;
        private string ticketDescription;
        private string followUp;
        private Priority priority;

        private TicketState ticketStateId;
        private TicketType ticketTypeId;
        private InternalUser raisedBy;
        private InternalUser assignedTo;

        #endregion
        public Ticket(Session session)
            : base(session)
        {
        }
        public override void AfterConstruction()
        {
            base.AfterConstruction();
            CreationDate = DateTime.Now;
        }

        #region Standalone Fields
        public int TicketNumber
        {
            get
            {
                return ticketNumber;
            }
            set
            {
                SetPropertyValue("TicketNumber", ref ticketNumber, value);
            }
        }
        public DateTime CreationDate
        {
            get
            {
                return creationDate;
            }
            set
            {
                SetPropertyValue("CreationDate", ref creationDate, value);
            }
        }
        public DateTime ErrorOccurDate
        {
            get
            {
                return errorOccurDate;
            }
            set
            {
                SetPropertyValue("ErrorOccurDate", ref errorOccurDate, value);
            }
        }
        public DateTime ErrorIdentifiedDate
        {
            get
            {
                return errorIdentifiedDate;
            }
            set
            {
                SetPropertyValue("errorIdentifiedDate", ref errorIdentifiedDate, value);
            }
        }
        public string TicketDescription
        {
            get
            {
                return ticketDescription;
            }
            set
            {
                SetPropertyValue("TicketDescription", ref ticketDescription, value);
            }
        }
        public string FollowUp
        {
            get
            {
                return followUp;
            }
            set
            {
                SetPropertyValue("FollowUp", ref followUp, value);
            }
        }
        public Priority Priority
        {
            get
            {
                return priority;
            }
            set
            {
                SetPropertyValue("Priority", ref priority, value);
            }
        }
        #endregion    }

        #region Foreign Keys
        [Association("TicketState-Tickets") , ImmediatePostData]
        public TicketState TicketStateId
        {
            get
            {
                return ticketStateId;
            }
            set
            {
                SetPropertyValue("TicketStateId", ref ticketStateId, value);
            }
        }
        [Association("TicketType-Tickets"), ImmediatePostData]
        public TicketType TicketTypeId
        {
            get
            {
                return ticketTypeId;
            }
            set
            {
                SetPropertyValue("TicketTypeId", ref ticketTypeId, value);
            }
        }
        [Association("InternalUser-Tickets"),ImmediatePostData]
        public InternalUser RaisedBy
        {
            get
            {
                return raisedBy;
            }
            set
            {
                SetPropertyValue("RaisedBy", ref raisedBy, value);
            }
        }
        [Association("InternalUser-Tickets"), ImmediatePostData]
        public InternalUser AssignedTo
        {
            get
            {
                return assignedTo;
            }
            set
            {
                SetPropertyValue("AssignedTo", ref assignedTo, value);
            }
        }
        #endregion

        #region OneToMany



        #endregion

    }

    public enum Priority
    {
        [ImageName("State_Priority_Low")]
        Low = 0,
        [ImageName("State_Priority_Normal")]
        Normal = 1,
        [ImageName("State_Priority_High")]
        High = 2
    }
}